#!/usr/bin/env sh
# Runs inside the rustfs-init compose service (minio/mc image).

set -eu

RUSTFS_ENDPOINT="${RUSTFS_ENDPOINT:-http://rustfs:9000}"
RUSTFS_ACCESS_KEY="${RUSTFS_ACCESS_KEY:-rustfsadmin}"
RUSTFS_SECRET_KEY="${RUSTFS_SECRET_KEY:-rustfsadmin}"
RUSTFS_ADMIN_USER="${RUSTFS_ADMIN_USER:-$RUSTFS_ACCESS_KEY}"
CREDS_FILE="${RUSTFS_CREDS_FILE:-/rustfs-out/credentials.env}"
S3_ENDPOINT="${S3_ENDPOINT:-$RUSTFS_ENDPOINT}"

# --- Bucket configuration -----------------------------------------------
# Space-separated list of env var names whose values are bucket names to
# create/ensure. Add or remove entries here to manage a new bucket — no
# other part of the script needs to change.
RUSTFS_MANAGED_BUCKET_VARS="${RUSTFS_MANAGED_BUCKET_VARS:-S3_BUCKET}"
# --------------------------------------------------------------------------

wait_for_rustfs() {
  echo "Waiting for RustFS S3 API at ${RUSTFS_ENDPOINT} ..."
  i=0
  while [ "$i" -lt 30 ]; do
    if mc alias set rustfs-probe "$RUSTFS_ENDPOINT" "$RUSTFS_ACCESS_KEY" "$RUSTFS_SECRET_KEY" >/dev/null 2>&1; then
      mc alias remove rustfs-probe >/dev/null 2>&1 || true
      echo "RustFS is ready."
      return 0
    fi
    i=$((i + 1))
    sleep 2
  done
  echo "RustFS did not become reachable in time (${RUSTFS_ENDPOINT})." >&2
  exit 1
}

ensure_buckets() {
  mc alias set rustfs "$RUSTFS_ENDPOINT" "$RUSTFS_ACCESS_KEY" "$RUSTFS_SECRET_KEY" >/dev/null

  for var in $RUSTFS_MANAGED_BUCKET_VARS; do
    bucket=$(eval "printf '%s' \"\${$var:-}\"")
    if [ -z "$bucket" ]; then
      echo "Skipping empty ${var}."
      continue
    fi
    echo "Ensuring bucket: ${bucket}"
    mc mb --ignore-existing "rustfs/${bucket}"
  done
}

write_credentials() {
  access_key="$1"
  secret_key="$2"
  mkdir -p "$(dirname "$CREDS_FILE")"
  umask 077
  {
    echo "# Generated by docker/rustfs/init.sh — merge into .env (do not commit)"
    echo "AWS_ACCESS_KEY_ID=${access_key}"
    echo "AWS_SECRET_ACCESS_KEY=${secret_key}"
    echo "AWS_REGION=${AWS_REGION:-us-east-1}"
    echo "S3_ENDPOINT=${S3_ENDPOINT}"
    for var in $RUSTFS_MANAGED_BUCKET_VARS; do
      bucket=$(eval "printf '%s' \"\${$var:-}\"")
      echo "${var}=${bucket}"
    done
  } >"$CREDS_FILE"
  chmod 600 "$CREDS_FILE"
  echo "Wrote app credentials to ${CREDS_FILE}"
}

ensure_app_credentials() {
  if [ -f "$CREDS_FILE" ] && [ "${RUSTFS_INIT_FORCE_REGEN:-}" != "1" ]; then
    echo "Credentials already exist at ${CREDS_FILE} (set RUSTFS_INIT_FORCE_REGEN=1 to regenerate)."
    return 0
  fi

  if [ "${RUSTFS_INIT_SKIP_CREDS:-}" = "1" ]; then
    echo "Skipping credential generation (RUSTFS_INIT_SKIP_CREDS=1)."
    return 0
  fi

  mc alias set rustfs "$RUSTFS_ENDPOINT" "$RUSTFS_ACCESS_KEY" "$RUSTFS_SECRET_KEY" >/dev/null
  echo "Creating RustFS service account for app use ..."
  svc_out=$(mc admin user svcacct add rustfs "$RUSTFS_ADMIN_USER")
  access_key=""
  secret_key=""
  while IFS= read -r line; do
    case "$line" in
      "Access Key:"*) access_key="${line#Access Key: }" ;;
      "Secret Key:"*) secret_key="${line#Secret Key: }" ;;
    esac
  done <<EOF
$svc_out
EOF

  if [ -z "$access_key" ] || [ -z "$secret_key" ]; then
    echo "Failed to parse service account output:" >&2
    printf '%s\n' "$svc_out" >&2
    exit 1
  fi

  write_credentials "$access_key" "$secret_key"
}

wait_for_rustfs
ensure_buckets
ensure_app_credentials

echo "RustFS init finished."